image: golang:1.21

stages:
    - test

before_script:
    - git clone https://github.com/magefile/mage.git
    - cd mage
    - go run bootstrap.go install

lint:
    stage: test
    script:
        - mage lint

unit_tests:
    stage: test
    script:
        - mage test
    coverage: /total:\s+\(statements\)\s+(\d+\.\d+)%/
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        reports:
            junit:
                - 'tests.xml'